### PR TITLE
auto update

### PR DESCRIPTION
**Pull request by michaelknoch**

### CODE REVIEW

**Comment by timoweiss** [comment]
Can I somehow help to proceed with this? :)

**Comment by michaelknoch** [comment]
its finished, i guess @timoweiss

**Comment by timoweiss** [comment]
@michaelknoch nice 👍 
what do you think about adding a build cmd for the frontend in the root package.json.
something like `cd renderer/ && npm run build && cd -`. This could then be added to the dist cmd.

**Comment by timoweiss** [comment]
I think maintaining this extra file `auto_updater.json` shouldn't be a big deal.

**Pull request merged**
